# Site settings
title: English Efficiently
tagline: Uč se anglicky osobně nebo online
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/englishefficiently" # the subpath of your site, e.g. /blog
url: "https://prochazkova.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Plugins
plugins: ["jekyll-paginate"]

# Pagination
paginate: 4
paginate_path: "/englishefficiently/blog/page:num/"